### ISSUE TITLE
前端主题切换方案

### ISSUE THREAD

**Issue by fangmd** [fangmd/blogsource#107]

**Comment by fangmd** [comment]
## 方案一：


```css
:root {
  --color-primary: 0, 0, 255;

  --foreground-rgb: 0, 0, 0;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color-primary: 255, 0, 0;

    --foreground-rgb: 255, 255, 255;
  }
}

.dark {
  color-scheme: dark;
}

body {
  color: rgb(var(--foreground-rgb));
}

.text-primary {
  color: rgb(var(--color-primary));
}
```

- `color-scheme` 不兼容 IE 浏览器
