### ISSUE TITLE
CSS 记录

### ISSUE THREAD

**Issue by fangmd** [fangmd/blogsource#46]

**Comment by fangmd** [comment]
# 文字限制行数，结尾省略

```
overflow: hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 1;
-webkit-box-orient: vertical;
```

>-webkit-line-clamp: 2;（行数）


## 设置文字不换行

```
 .el-table .cell {
 	white-space: nowrap;
  	overflow: hidden;
  	text-overflow: ellipsis;
}
```

**Comment by fangmd** [comment]
1

**Comment by fangmd** [comment]
## font-weight 和 font-family 字体粗细类型的对应关系

100 - Thin

200 - Extra Light (Ultra Light)

300 - Light

400 - Regular (Normal、Book、Roman)

500 - Medium

600 - Semi Bold (Demi Bold)

700 - Bold

800 - Extra Bold (Ultra Bold)

900 - Black (Heavy)

**Comment by fangmd** [comment]
## 隐藏滚动条

```
.list{
    overflow: -moz-scrollbars-none;
    -ms-overflow-style: none;
    &::-webkit-scrollbar {
      width: 0 !important;
    }
}
```

```
.element::-webkit-scrollbar { width: 0 !important }
IE 10+

.element { -ms-overflow-style: none; }
Firefox

.element { overflow: -moz-scrollbars-none; }
```

**Comment by fangmd** [comment]
## 下拉菜单

### 动画

```
.list-hide {
    visibility: hidden;
    transition: all 0.15s ease-in;
    max-height: 0 !important;
}

.list{
    max-height: 390px;
    overflow-y: auto;
    padding: 8px 0;
    transition: all 0.25s ease-out;
}
```

**Comment by fangmd** [comment]
## 元素覆盖的同时不影响被覆盖的元素的 hover 和 点击

上层元素添加下面的属性

```
pointer-events: none
```

**Comment by fangmd** [comment]
## 图片覆盖动画效果

>https://www.deepal.com.cn/index

![Kapture 2022-08-12 at 14 51 49](https://user-images.githubusercontent.com/16234953/184300451-495c9597-c88b-45ea-a91e-338ded640648.gif)

实现方式：2张图片互相覆盖，新的图片做个现实动画

```
.floor6___VB70- .car___63wqu.move___HG9-F {
    animation: run___24oQ6 1.5s;
    animation-fill-mode: forwards
}

@keyframes run___24oQ6 {
    0% {
        -webkit-clip-path: polygon(0 0,100% 0,100% 100%,0 100%);
        clip-path: polygon(0 0,100% 0,100% 100%,0 100%)
    }

    to {
        -webkit-clip-path: polygon(0 0,20% 0,0 100%,0 100%);
        clip-path: polygon(0 0,20% 0,0 100%,0 100%)
    }
}
```

**Comment by fangmd** [comment]
## object-fit 兼容问题处理

https://github.com/constancecchen/object-fit-polyfill

**Comment by fangmd** [comment]
## flex 水平滚动

```
父容器
overflow-x: auto;
```

**Comment by fangmd** [comment]
## 阴影效果

```
box-shadow: 0 0 24px rgb(81 87 103 / 16%);
```

svg 阴影效果:

```
filter: drop-shadow(3px 3px 2px rgba(0, 0, 0, 0.2));
```

**Comment by fangmd** [comment]
## css 虚线

<img width="582" alt="image" src="https://user-images.githubusercontent.com/16234953/210292601-b2d4ba28-e24b-41b3-86a4-a87f69cd2525.png">


```
    <div style="background: #ffffff; color: #000000">
      <h1>虚线 demo</h1>
      <div class="box card3"></div>
      <div class="box card4"></div>
      <div class="box card5">css模拟边框的虚线</div>
    </div>
```

```css
<style>
.card3 {
  height: 1px;
  box-sizing: border-box;
  background-image: linear-gradient(
    to right,
    #000 35%,
    rgba(255, 255, 255, 0) 0%
  ); /* 35%设置虚线点x轴上的长度 */
  background-position: bottom; /* top配置上边框位置的虚线 */
  background-size: 10px 1px; /* 第一个参数设置虚线点的间距；第二个参数设置虚线点y轴上的长度 */
  background-repeat: repeat-x;
}
.card4 {
  height: 50px;
  box-sizing: border-box;
  background-image: linear-gradient(
    #000 35%,
    rgba(255, 255, 255, 0) 0%
  ); /* 35%设置虚线点y轴上的长度 */
  background-position: left; /* right配置右边框位置的虚线 */
  background-size: 1px 10px; /* 第一个参数设置虚线点x轴上的长度；第二个参数设置虚线点的间距 */
  background-repeat: repeat-y;
}
.card5 {
  margin-top: 20px;
  box-sizing: border-box;
  border: 1px dashed transparent;
  background: linear-gradient(#fff, #fff) padding-box,
    repeating-linear-gradient(-45deg, #000 0, #000 0.3em, #fff 0, #fff 0.6em);
  /* 0.3em设置虚线点的宽度或长度；0.6em设置虚线点的间距 */
}
</style>
```
